services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    # ports:
    #   - '3000:3000'
    environment:
      - GF_ELASTICSEARCH_URL=http://elasticsearch:9200
      - GF_ELASTICSEARCH_INDEX=@timestamp
      - GF_INSTALL_PLUGINS=volkovlabs-form-panel
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./app/grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - elasticsearch

  bettercap:
    image: bettercap/bettercap
    container_name: bettercap
    network_mode: host
    restart: unless-stopped
    # ports:
    #   - '80:80'
    #   - '8081:8081'
    cap_add:
      - NET_ADMIN
    volumes:
      - ./app/bettercap_config:/root/.bettercap
    command: -caplet http-ui -eval caplets.update -eval ui.update

  elasticsearch:
    image: elasticsearch:8.13.0
    container_name: elasticsearch
    restart: unless-stopped
    # ports:
    #   - '9200:9200'
    volumes:
      - elasticsearch-storage:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
       # Paramètres de sécurité Elasticsearch
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=P@55aran
      - xpack.security.authc.api_key.enabled=true

  logstash:
    image: logstash:8.13.0
    container_name: logstash
    restart: unless-stopped
    volumes:
      - ./app/logstash/config:/usr/share/logstash/config
      - ./app/logstash/pipeline:/usr/share/logstash/pipeline
    # ports:
    #   - "5044:5044"
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - ELASTICSEARCH_USER=elastic
      - ELASTICSEARCH_PASSWORD=P@55aran
      - ELASTICSEARCH_SSL_ENABLED=true
      - ELASTICSEARCH_SSL_VERIFICATION_MODE=false
    depends_on:
      - elasticsearch
  
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - '443:443'
      # - '8443:8443'
    volumes:
      - ./app/nginx/conf.d:/etc/nginx/conf.d
      - ./app/nginx/certs:/etc/nginx/certs
    depends_on:
      - grafana

volumes:
  grafana-storage:
  elasticsearch-storage: