version: '3.8'
services:

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./app/grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - elasticsearch

  bettercap:
    image: bettercap/bettercap
    container_name: bettercap
    network_mode: host
    restart: unless-stopped
    ports:
      - '80:80'
      - '8081:8081'
    cap_add:
      - NET_ADMIN
    volumes:
      - ./app/bettercap_config:/root/.bettercap
    command: -caplet http-ui

  elasticsearch:
    image: elasticsearch:8.13.0
    container_name: elasticsearch
    restart: unless-stopped
    ports:
      - '9200:9200'
    volumes:
      - elasticsearch-storage:/usr/share/elasticsearch/data
    environment:
      - ELASTIC_PASSWORD=changeme

  logstash:
    image: logstash:8.13.0
    container_name: logstash
    restart: unless-stopped
    volumes:
      - ./app/logstash/:/usr/share/logstash/pipeline
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - ELASTICSEARCH_USER=elastic
      - ELASTICSEARCH_PASSWORD=changeme
      - ELASTICSEARCH_SSL_ENABLED=rue
      - ELASTICSEARCH_SSL_VERIFICATION_MODE=false
    depends_on:
      - elasticsearch

volumes:
  grafana-storage:
  elasticsearch-storage: